// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: base.proto
#ifndef GRPC_base_2eproto__INCLUDED
#define GRPC_base_2eproto__INCLUDED

#include "base.pb.h"

#include <grpc++/impl/internal_stub.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/async_unary_call.h>
#include <grpc++/status.h>
#include <grpc++/stream.h>

namespace grpc {
class CompletionQueue;
class ChannelInterface;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace common {

}  // namespace common


#endif  // GRPC_base_2eproto__INCLUDED
