// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: base.proto

#include "base.pb.h"
#include "base.grpc.pb.h"

#include <grpc++/async_unary_call.h>
#include <grpc++/channel_interface.h>
#include <grpc++/impl/client_unary_call.h>
#include <grpc++/impl/rpc_service_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/stream.h>
namespace common {

}  // namespace common

