// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: event_store.proto
#ifndef GRPC_event_5fstore_2eproto__INCLUDED
#define GRPC_event_5fstore_2eproto__INCLUDED

#include "event_store.pb.h"

#include <grpc++/impl/internal_stub.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/status.h>

namespace grpc {
class CompletionQueue;
class ChannelInterface;
class RpcService;
class ServerContext;
template <class InMessage> class ClientReader;
template <class OutMessage> class ServerWriter;
template <class OutMessage> class ClientAsyncReader;
template <class InMessage> class ServerAsyncWriter;
}  // namespace grpc

namespace event {

class EventStore GRPC_FINAL {
 public:
  class Stub GRPC_FINAL : public ::grpc::InternalStub {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::Event>> get(::grpc::ClientContext* context, const ::Uuid& request);
    std::unique_ptr< ::grpc::ClientAsyncReader< ::Event>> Asyncget(::grpc::ClientContext* context, const ::Uuid& request, ::grpc::CompletionQueue* cq, void* tag);
   private:
    const ::grpc::RpcMethod rpcmethod_get_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status get(::grpc::ServerContext* context, const ::Uuid* request, ::grpc::ServerWriter< ::Event>* writer);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService(::grpc::CompletionQueue* cq);
    ~AsyncService() {};
    void Requestget(::grpc::ServerContext* context, ::Uuid* request, ::grpc::ServerAsyncWriter< ::Event>* writer, ::grpc::CompletionQueue* cq, void *tag);
  };
};

}  // namespace event


#endif  // GRPC_event_5fstore_2eproto__INCLUDED
