// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: event_store.proto

#include "event_store.pb.h"
#include "event_store.grpc.pb.h"

#include <grpc++/async_unary_call.h>
#include <grpc++/channel_interface.h>
#include <grpc++/impl/client_unary_call.h>
#include <grpc++/impl/rpc_service_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/stream.h>
namespace event {

static const char* EventStore_method_names[] = {
  "/event.EventStore/get",
};

std::unique_ptr< EventStore::Stub> EventStore::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel) {
  std::unique_ptr< EventStore::Stub> stub(new EventStore::Stub(channel));
  return stub;
}

EventStore::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : ::grpc::InternalStub(channel), rpcmethod_get_(EventStore_method_names[0], ::grpc::RpcMethod::SERVER_STREAMING, channel->RegisterMethod(EventStore_method_names[0]))
  {}

std::unique_ptr< ::grpc::ClientReader< ::Event>> EventStore::Stub::get(::grpc::ClientContext* context, const ::Uuid& request) {
  return std::unique_ptr< ::grpc::ClientReader< ::Event>>(new ::grpc::ClientReader< ::Event>(channel(),rpcmethod_get_, context, request));
}

std::unique_ptr< ::grpc::ClientAsyncReader< ::Event>> EventStore::Stub::Asyncget(::grpc::ClientContext* context, const ::Uuid& request, ::grpc::CompletionQueue* cq, void* tag) {
  return std::unique_ptr< ::grpc::ClientAsyncReader< ::Event>>(new ::grpc::ClientAsyncReader< ::Event>(channel(), cq, rpcmethod_get_, context, request, tag));
}

EventStore::AsyncService::AsyncService(::grpc::CompletionQueue* cq) : ::grpc::AsynchronousService(cq, EventStore_method_names, 1) {}

EventStore::Service::~Service() {
  delete service_;
}

::grpc::Status EventStore::Service::get(::grpc::ServerContext* context, const ::Uuid* request, ::grpc::ServerWriter< ::Event>* writer) {
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED);
}

void EventStore::AsyncService::Requestget(::grpc::ServerContext* context, ::Uuid* request, ::grpc::ServerAsyncWriter< ::Event>* writer, ::grpc::CompletionQueue* cq, void* tag) {
  AsynchronousService::RequestServerStreaming(0, context, request, writer, cq, tag);
}

::grpc::RpcService* EventStore::Service::service() {
  if (service_ != nullptr) {
    return service_;
  }
  service_ = new ::grpc::RpcService();
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      EventStore_method_names[0],
      ::grpc::RpcMethod::SERVER_STREAMING,
      new ::grpc::ServerStreamingHandler< EventStore::Service, ::Uuid, ::Event>(
          std::mem_fn(&EventStore::Service::get), this),
      new ::Uuid, new ::Event));
  return service_;
}


}  // namespace event

