// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: eventbus.proto
#ifndef GRPC_eventbus_2eproto__INCLUDED
#define GRPC_eventbus_2eproto__INCLUDED

#include "eventbus.pb.h"

#include <grpc++/impl/internal_stub.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/async_unary_call.h>
#include <grpc++/status.h>
#include <grpc++/stream.h>

namespace grpc {
class CompletionQueue;
class ChannelInterface;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace event {

class EventBus GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status publish(::grpc::ClientContext* context, const ::common::Event& request, ::common::ExecutionReport* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::ExecutionReport>> Asyncpublish(::grpc::ClientContext* context, const ::common::Event& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::ExecutionReport>>(AsyncpublishRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::ExecutionReport>* AsyncpublishRaw(::grpc::ClientContext* context, const ::common::Event& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface, public ::grpc::InternalStub {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status publish(::grpc::ClientContext* context, const ::common::Event& request, ::common::ExecutionReport* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::ExecutionReport>> Asyncpublish(::grpc::ClientContext* context, const ::common::Event& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::ExecutionReport>>(AsyncpublishRaw(context, request, cq));
    }

   private:
    ::grpc::ClientAsyncResponseReader< ::common::ExecutionReport>* AsyncpublishRaw(::grpc::ClientContext* context, const ::common::Event& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_publish_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status publish(::grpc::ServerContext* context, const ::common::Event* request, ::common::ExecutionReport* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void Requestpublish(::grpc::ServerContext* context, ::common::Event* request, ::grpc::ServerAsyncResponseWriter< ::common::ExecutionReport>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace event


#endif  // GRPC_eventbus_2eproto__INCLUDED
